### ISSUE TITLE
Error during setup of component argon40

### ISSUE THREAD

**Issue by liamlain** [adamoutler/HassOSArgonOneAddon#72]
Each time restart HA ,this error showing up

Core: 2024.5.3
Supervisor: 2024.05.1
OS: 12.3
ArgonOne Active Cooling: 30a

```
Logger: homeassistant.setup
Source: setup.py:404
First occurred: 11:01:35 PM (1 occurrences)
Last logged: 11:01:35 PM

Error during setup of component argon40
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 404, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/argon40/__init__.py", line 71, in async_setup
    GPIO.add_event_detect(shutdown_pin, GPIO.BOTH, callback=event_detect_callback)
RuntimeError: Failed to add edge detection
```

**Comment by adamoutler** [comment]
Looks like a problem with your system.  This isn't an app error.
